### ISSUE TITLE
Add newline helper

### ISSUE THREAD

**Issue by mattkleker** [mattkleker/accounting-app#11]
@samselikoff need help with this one.  I've got the display looking like I want it, but having trouble adding a newline.  

Here's someone's explanation: http://stackoverflow.com/questions/12331077/does-handlebars-js-replace-newline-characters-with-br

This isn't using ember-cli, so it looks a lot different from what's generated when I do ```ember generate helper breakline```.  I'm not sure I know exactly how these work.

**Comment by samselikoff** [comment]
You can also do `{{{html}}}` to not escape anything, if your variable has `<br>` tags in it.

**Comment by mattkleker** [comment]
Worked thanks.  I'd seen a comment somewhere on stackoverflow that said not to do this as it opens you up to vulnerabilities, but probably no big deal in this case.

**Comment by samselikoff** [comment]
Yep it does, but that's if you're doing it with user-entered text.

E.g. 

    {{input value=firstName}}

If user entered `<script>alert('pwned');</script>` and you had

    Hello, {{{firstName}}}!

then the script would be executed.

**Comment by mattkleker** [comment]
Got it - thanks

**Comment by mattkleker** [comment]
This has started returning ```undefined``` in the app if ```middleMonthEquation``` doesn't return anything.  When I changed it from triple to double brackets it stopped doing that, but then of course didn't execute the script.  

this must be an issue with the new ember-cli?
